### ISSUE TITLE
add option to open on next viewColumn (split mode)

### ISSUE THREAD

**Issue by pungggi** [lunow/vscode-correspoding-files#1]
Thank you for this little helper. I would love to have the possibility to open the file in Split 
![image](https://user-images.githubusercontent.com/5635709/31640922-939f1fbc-b2e1-11e7-8d74-fad2f63f7d4b.png)
![image](https://user-images.githubusercontent.com/5635709/31640956-cf2ba0b4-b2e1-11e7-9647-9578342918ba.png)

You may add the options here>https://github.com/lunow/vscode-correspoding-files/blob/master/extension.js#L100

viewColumn > https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocumentShowOptions

**Comment by lunow** [comment]
thanks for your comment! any PR warmly welcome, at the moment my time is very limited, but the extension works great so far. would love to extend it...
